frontwindshieldscameraMake: 
	gcc frontwindshieldcamera.c -o front-windshield-camera
	clear
	@echo "frontwindshieldcamera ès stato creato correttamente."

forwardingfacingradarMake:
	gcc forwardingfacingradar.c -o forwarding-facing-camera
	clear
	@echo "forwardingfacingradar è stato creato correttamente."
surroundviewcameraMake:
	gcc surroundviewcamera.c -o surround-view-camera
	clear
	@echo "svc è stato creato correttamente."
parkassistMake: 
	gcc parkassist.c -o park-assist
	clear
	@echo "pa è stato creato correttamente."

allMake:
	gcc frontwindshieldcamera.c -o front-windshield-camera
	gcc forwardingfacingradar.c -o forwarding-facing-radar
	gcc surroundviewcamera.c -o surround-view-camera
	gcc parkassist.c -o park-assist
	gcc steerbywire.c -o steer-by-wire
	gcc brakebywire.c -o brake-by-wire
	gcc throttlebycontrol.c -o throttle-by-control
	gcc ecu.c -o ecu
	gcc hmi.c -o hmi
	@echo "Tutti i file sono stati creati correttamente."